### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by rezobe** [Ensembles/ert#1489]
Although all header files seems to be included, MSYS make stops with the following error message:

Linking C shared library ../../lib/libert_util.dll
MakeFiles/ert_util.dir/objects.a(util.c.obj): In function `util_make_datetime_u
tc__':
x:\ert\ert-2.1.3\build-tmp\libert_util\src/../../../libert_util/src/util.c:3349:
 undefined reference to `_mkgmtime'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [lib/libert_util.dll] Error 1
make[1]: *** [libert_util/src/CMakeFiles/ert_util.dir/all] Error 2
make: *** [all] Error 2

**Comment by pgdr** [comment]
Hi, @rezobe and thanks for reporting this issue.  We have as of today frozen this repository, and development is now happening on [Statoil/libecl](https://github.com/Statoil/libecl).

I hope you can take the time to file the issue there instead of here.

I also want to mention that none of the developers are running Microsoft Windows, so some hickups are to be expected.  We want to help you however, did you read [Windows.txt](https://github.com/Statoil/libecl/blob/master/Windows.txt)?

[Go here if you rather want to install Ubuntu.](https://www.ubuntu.com/download/desktop)

**Comment by pgdr** [comment]
It might perhaps be an issue with 32-bits `MinGW`, and that we have to explicitly call `_mkgmtime32` in the case that windows 32 is used.

**Comment by jokva** [comment]
That shouldn't be necessary, that's only when you need to force it to be 32-bit. Using 64_t values on 32-bit systems should be just fine.

**Comment by pgdr** [comment]
What I tried to say was that in MinGW32, there is no symbol called `_mkgmtime`, but there is one called `_mkgmtime32`.  I might of course be very wrong.

[Ubuntu has the correct symbols, though.](https://www.ubuntu.com/download/desktop)

**Comment by jokva** [comment]
I think this is a known issue with mingw. https://sourceforge.net/p/mingw-w64/bugs/473/ What compiler are you using, @rezobe?

**Comment by pgdr** [comment]
If you want to test the theory, simply go to `util.c:3349` (or thereabout) and update `_mkgmtime` to `_mkgmtime32`.

**Comment by jokva** [comment]
@pgdr There is no symbol for _mkgmtime because it's an inline function/macro that expands to _mkgmtim64. According to the documentation anyway.
